In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**Swiggy Data 1**

In [ ]:
#==========================
# Swiggy Data 1
#==========================

data = "/content/swiggy.xlsx"

df = pd.read_excel(data)
df.head()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [ ]:
df.tail()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
8675,464626,Panjarapole Cross Road,Ahmedabad,Malt Pizza,500,2.9,80,Pizzas,Navrangpura,40
8676,465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,200,2.9,80,South Indian,Rohini,28
8677,465872,Rohini,Delhi,Chinese Kitchen King,150,2.9,80,"Chinese,Snacks,Tandoor",Rohini,58
8678,465990,Rohini,Delhi,Shree Ram Paratha Wala,150,2.9,80,"North Indian,Indian,Snacks",Rohini,28
8679,466488,Navrangpura,Ahmedabad,Sassy Street,250,2.9,80,"Chaat,Snacks,Chinese",Navrangpura,44

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8680 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             8680 non-null   int64
 1   Area           8680 non-null   object
 2   City           8680 non-null   object
 3   Restaurant     8680 non-null   object
 4   Price          8680 non-null   int64
 5   Avg ratings    8680 non-null   float64
 6   Total ratings  8680 non-null   int64
 7   Food type      8680 non-null   object
 8   Address        8680 non-null   object
 9   Delivery time  8680 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 678.3+ KB

In [ ]:
df.describe()

                  ID        Price  Avg ratings  Total ratings  Delivery time
count    8680.000000  8680.000000  8680.000000    8680.000000    8680.000000
mean   244812.071429   348.444470     3.655104     156.634793      53.967051
std    158671.617188   230.940074     0.647629     391.448014      14.292335
min       211.000000     0.000000     2.000000      20.000000      20.000000
25%     72664.000000   200.000000     2.900000      50.000000      44.000000
50%    283442.000000   300.000000     3.900000      80.000000      53.000000
75%    393425.250000   400.000000     4.200000     100.000000      64.000000
max    466928.000000  2500.000000     5.000000   10000.000000     109.000000

In [ ]:
df.shape

(8680, 10)

In [ ]:
df.isnull()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8675,False,False,False,False,False,False,False,False,False,False
8676,False,False,False,False,False,False,False,False,False,False
8677,False,False,False,False,False,False,False,False,False,False
8678,False,False,False,False,False,False,False,False,False,False
8679,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

ID               0
Area             0
City             0
Restaurant       0
Price            0
Avg ratings      0
Total ratings    0
Food type        0
Address          0
Delivery time    0
dtype: int64

In [ ]:
df.fillna("NA")

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63
...,...,...,...,...,...,...,...,...,...,...
8675,464626,Panjarapole Cross Road,Ahmedabad,Malt Pizza,500,2.9,80,Pizzas,Navrangpura,40
8676,465835,Rohini,Delhi,Jay Mata Ji Home Kitchen,200,2.9,80,South Indian,Rohini,28
8677,465872,Rohini,Delhi,Chinese Kitchen King,150,2.9,80,"Chinese,Snacks,Tandoor",Rohini,58
8678,465990,Rohini,Delhi,Shree Ram Paratha Wala,150,2.9,80,"North Indian,Indian,Snacks",Rohini,28
8679,466488,Navrangpura,Ahmedabad,Sassy Street,250,2.9,80,"Chaat,Snacks,Chinese",Navrangpura,44

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
print("Operations On Price Column: ")
print()
print("Avg Price")
print(df["Price"].mean())
print("================")

print("Max Price")
print(df["Price"].max())
print("================")

print("Min Price")
print(df["Price"].min())
print("================")

print("Median of Price")
print(df["Price"].median())
print("================")

print("Mode of Price")
print(df["Price"].mode())
print("================")

Operations On Price Column:

Avg Price
348.4444700460829
================
Max Price
2500
================
Min Price
0
================
Median of Price
300.0
================
Mode of Price
0    300
Name: Price, dtype: int64
================

In [ ]:
print("Operations On Delivery Time Column: ")
print()
print("Avg Time")
print(df["Delivery time"].mean())
print("================")

print("Max Time")
print(df["Delivery time"].max())
print("================")

print("Min Time")
print(df["Delivery time"].min())
print("================")

print("Median of Time")
print(df["Delivery time"].median())
print("================")

print("Mode of Time")
print(df["Delivery time"].mode())
print("================")

Operations On Delivery Time Column:

Avg Time
53.96705069124424
================
Max Time
109
================
Min Time
20
================
Median of Time
53.0
================
Mode of Time
0    52
Name: Delivery time, dtype: int64
================

In [ ]:
print(df["City"].unique())

['Bangalore' 'Hyderabad' 'Mumbai' 'Pune' 'Kolkata' 'Delhi' 'Chennai'
 'Ahmedabad' 'Surat']

In [ ]:
print("Number Of Restaurant by Cities")
print()
print(df["City"].value_counts())

Number Of Restaurant by Cities

City
Kolkata      1346
Mumbai       1277
Chennai      1106
Pune         1090
Hyderabad    1075
Bangalore     946
Ahmedabad     717
Delhi         611
Surat         512
Name: count, dtype: int64

In [ ]:
print("Operations On Total Ratings(Count) Column: ")
print()
print("Avg Count of Ratings")
print(df["Total ratings"].mean())
print("================")

print("Max Count of Ratings")
print(df["Total ratings"].max())
print("================")

print("Min Count of Ratings")
print(df["Total ratings"].min())
print("================")

print("Median Count of Ratings")
print(df["Total ratings"].median())
print("================")

print("Mode Count of Ratings")
print(df["Total ratings"].mode())
print("================")

Operations On Total Ratings(Count) Column:

Avg Count of Ratings
156.6347926267281
================
Max Count of Ratings
10000
================
Min Count of Ratings
20
================
Median Count of Ratings
80.0
================
Mode Count of Ratings
0    80
Name: Total ratings, dtype: int64
================

**Swiggy Data 2**

In [ ]:
#==========================
# Swiggy Data 1
#==========================

data = "/content/swiggy_file .xlsx"

df = pd.read_excel(data)
df.head()

,Restaurant Name,Cuisine,Rating,Number of ratings,Average Price,Number of Offers,Offer Name,Area,Pure Veg,Location
0,La Pino'Z Pizza,"Pizzas, Pastas",4,10,250,2,FLAT DEAL\nFLAT ₹ 125 OFF\nUSE FLAT ₹125ABOVE ...,LALA LAJPAT RAI MARKET,No,Abohar
1,The Second Wife,"Indian, North Indian",3.6,50,250,2,"30% OFF UPTO 75\nUSE TRYNEWABOVE 149, FLAT ₹ 1...",Central Abohar,No,Abohar
2,Tasty Bites,"Italian, Beverages",3.8,10,200,1,FLAT ₹ 120 OFF\nUSE AXIS120ABOVE 500,Central Abohar,Yes,Abohar
3,Food Studio,"Pizzas, Burgers",3.5,8,49,5,"50% OFF UPTO 100\nUSE TRYNEWABOVE 129, FLAT DE...",Central Abohar,Yes,Abohar
4,Roll Express,"Fast Food, Snacks",4.3,100,200,2,DEAL OF DAY\n10% OFF UPTO 40\nUSE STEALDEALABO...,Circular Road,No,Abohar

In [ ]:
df.tail()

,Restaurant Name,Cuisine,Rating,Number of ratings,Average Price,Number of Offers,Offer Name,Area,Pure Veg,Location
140652,Yummy Momo'S Cafe,"Chinese, Fast Food",4.6,3,100,3,"20% OFF UPTO 50\nUSE TRYNEWABOVE 149, FLAT ₹ 1...",Yavatmal Locality,Yes,Yavatmal
140653,CAFE FIRST FLOOR,"Beverages, Snacks",3.2,3,200,2,"FLAT ₹ 120 OFF\nUSE AXIS120ABOVE 500, FLAT ₹ 5...",Yavatmal City,Yes,Yavatmal
140654,Cafe Coffee Aani Barach Kahi,Snacks,3.2,50,150,2,"FLAT ₹ 120 OFF\nUSE AXIS120ABOVE 500, FLAT ₹ 5...",Yavatmal Locality,Yes,Yavatmal
140655,Patil Family Restaurant,"North Indian, Biryani",4.3,9,200,2,"FLAT ₹ 120 OFF\nUSE AXIS120ABOVE 500, FLAT ₹ 5...",Yavatmal Locality,No,Yavatmal
140656,Prabhakar Mama Cha Dhaba,North Indian,,,350,2,"FLAT ₹ 120 OFF\nUSE AXIS120ABOVE 500, FLAT ₹ 5...",Yavatmal Locality,No,Yavatmal

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140657 entries, 0 to 140656
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Restaurant Name     140657 non-null  object
 1   Cuisine             140630 non-null  object
 2   Rating              140657 non-null  object
 3   Number of  ratings  140657 non-null  object
 4   Average Price       140657 non-null  int64
 5   Number of Offers    140657 non-null  int64
 6   Offer Name          138849 non-null  object
 7   Area                140655 non-null  object
 8   Pure Veg            140657 non-null  object
 9   Location            140657 non-null  object
dtypes: int64(2), object(8)
memory usage: 10.7+ MB

In [ ]:
df.describe()

       Average Price  Number of Offers
count  140657.000000     140657.000000
mean      270.081489          3.187890
std       550.322759          1.583943
min         1.000000          0.000000
25%       200.000000          1.000000
50%       250.000000          4.000000
75%       300.000000          5.000000
max    199246.000000          5.000000

In [ ]:
df.columns

Index(['Restaurant Name', 'Cuisine', 'Rating', 'Number of  ratings',
       'Average Price', 'Number of Offers', 'Offer Name', 'Area', 'Pure Veg',
       'Location'],
      dtype='object')

In [ ]:
df.shape

(140657, 10)

In [ ]:
df.isnull()

,Restaurant Name,Cuisine,Rating,Number of ratings,Average Price,Number of Offers,Offer Name,Area,Pure Veg,Location
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
140652,False,False,False,False,False,False,False,False,False,False
140653,False,False,False,False,False,False,False,False,False,False
140654,False,False,False,False,False,False,False,False,False,False
140655,False,False,False,False,False,False,False,False,False,False
140656,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Restaurant Name          0
Cuisine                 27
Rating                   0
Number of  ratings       0
Average Price            0
Number of Offers         0
Offer Name            1808
Area                     2
Pure Veg                 0
Location                 0
dtype: int64

In [ ]:
df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
140652    False
140653    False
140654    False
140655    False
140656    False
Length: 140657, dtype: bool

In [ ]:
print(df.duplicated().sum())

1336

In [ ]:
print("Operations On Number of Offers Column: ")
print()
print("Avg Number of Offers")
print(df["Number of Offers"].mean())
print("================")

print("Max Number of Offers")
print(df["Number of Offers"].max())
print("================")

print("Min Number of Offers")
print(df["Number of Offers"].min())
print("================")

print("Median of Number of Offers")
print(df["Number of Offers"].median())
print("================")

print("Mode of Number of Offers")
print(df["Number of Offers"].mode())
print("================")

Operations On Number of Offers Column:

Avg Number of Offers
3.1878896891018575
================
Max Number of Offers
5
================
Min Number of Offers
0
================
Median of Number of Offers
4.0
================
Mode of Number of Offers
0    4
Name: Number of Offers, dtype: int64
================

In [ ]:
print("Operations On Price Column: ")
print()
print("Avg Price")
print(df["Average Price"].mean())
print("================")

print("Max Price")
print(df["Average Price"].max())
print("================")

print("Min Price")
print(df["Average Price"].min())
print("================")

print("Median of Price")
print(df["Average Price"].median())
print("================")

print("Mode of Price")
print(df["Average Price"].mode())
print("================")

Operations On Price Column:

Avg Price
270.0814890122781
================
Max Price
199246
================
Min Price
1
================
Median of Price
250.0
================
Mode of Price
0    200
Name: Average Price, dtype: int64
================